name: Compilar tesis LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-latex:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Compilar tesis con latexmk + biber
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_xelatex: false
          args: -pdf -interaction=nonstopmode -file-line-error
          extra_system_packages: "biber"

      - name: Subir PDF como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: tesis-pdf
          path: main.pdf
